sudo: false

dist: focal

language: python

python:
  - 3.6

install:
  - pip install -r setup_requirements.txt
  - sudo add-apt-repository -y ppa:longsleep/golang-backports
  - sudo apt update
  - sudo apt install -y golang-go-1.16
  - GOROOT=$(go1.16 env GOROOT) python setup.py install

script:
  - python -m unittest discover
