sudo: false

language: python

python:
  - 3.6

install:
  - pip install -r setup_requirements.txt
  - sudo add-apt-repository ppa:longsleep/golang-backports
  - sudo apt update
  - sudo apt install -y golang-go
  - python setup.py install

script:
  - python -m unittest discover

